"""fix user mall deletion cascade

Revision ID: 046ec1ac99e0
Revises: cc1b1472566f
Create Date: 2025-03-19 13:41:15.010570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '046ec1ac99e0'
down_revision: Union[str, None] = 'cc1b1472566f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_mall_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'malls', ['mall_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_mall_id_fkey', 'users', 'malls', ['mall_id'], ['id'])
    # ### end Alembic commands ###
