"""add_sequence_objects

Revision ID: 1ec7895c440e
Revises: 8ff727c4b0e6
Create Date: 2025-03-19 15:07:22.979604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ec7895c440e'
down_revision: Union[str, None] = '8ff727c4b0e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_mall_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'malls', ['mall_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_mall_id_fkey', 'users', 'malls', ['mall_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
