"""fix mall user relationship

Revision ID: 2e46d2429c3b
Revises: e9016cdabd4b
Create Date: 2025-03-19 13:23:11.207446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e46d2429c3b'
down_revision: Union[str, None] = 'e9016cdabd4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('malls_user_id_fkey', 'malls', type_='foreignkey')
    op.drop_column('malls', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('malls', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('malls_user_id_fkey', 'malls', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
