"""update user mall relationship with cascade delete

Revision ID: 7b6c413bd01e
Revises: da53b952f631
Create Date: 2025-03-19 14:18:06.943046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b6c413bd01e'
down_revision: Union[str, None] = 'da53b952f631'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_mall_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'malls', ['mall_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_mall_id_fkey', 'users', 'malls', ['mall_id'], ['id'])
    # ### end Alembic commands ###
