"""fix user mall relationship cascade

Revision ID: cc1b1472566f
Revises: 2e46d2429c3b
Create Date: 2025-03-19 13:37:29.372473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc1b1472566f'
down_revision: Union[str, None] = '2e46d2429c3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_mall_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'malls', ['mall_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_mall_id_fkey', 'users', 'malls', ['mall_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
