"""fix_user_delete_cascade

Revision ID: d1c9ec8131e4
Revises: aacf9405b3ec
Create Date: 2025-03-19 14:46:26.231582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1c9ec8131e4'
down_revision: Union[str, None] = 'aacf9405b3ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_mall_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'malls', ['mall_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_mall_id_fkey', 'users', 'malls', ['mall_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
