"""add user_id to mall

Revision ID: e9016cdabd4b
Revises: 7e47897ab86a
Create Date: 2025-03-19 13:18:23.973640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9016cdabd4b'
down_revision: Union[str, None] = '7e47897ab86a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('malls', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'malls', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'malls', type_='foreignkey')
    op.drop_column('malls', 'user_id')
    # ### end Alembic commands ###
